default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: school_development

test:
  <<: *default
  database: school_test

production:
  <<: *default
  database: school_production
